//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EricsTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int ID { get; set; }
        public int Health { get; set; }
        public int LVL { get; set; }
        public int AttackPower { get; set; }
        public Nullable<int> CurrentEXP { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Alive { get; set; }
        public Nullable<int> Weapon { get; set; }
    
        public virtual Weapon Weapon1 { get; set; }
    }
}
